version: '3.9'

services:

  # Runs the app in the development mode. The page will reload if you make edits.
  # You will also see any lint errors in the console.
  react-client-dev:
    container_name: react_client_dev
    build:
      context: .
      dockerfile: docker/react.dev.dockerfile
    image: oleksiivelychko/react-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    secrets:
      - source: server.crt
        target: /run/secrets/server.crt
      - source: server.key
        target: /run/secrets/server.key

  # It correctly bundles React in production mode and optimizes the build for the best performance.
  # The build is minified and the filenames include the hashes.
  react-client-prod:
    container_name: react_client_prod
    build:
      context: .
      dockerfile: docker/react.prod.dockerfile
    image: oleksiivelychko/react-prod
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
    secrets:
      - source: server.crt
        target: /run/secrets/server.crt
      - source: server.key
        target: /run/secrets/server.key

secrets:
  server.crt:
    file: /home/alex/GitHub/self-signed-certificates/certs/localhost.crt
  server.key:
    file: /home/alex/GitHub/self-signed-certificates/certs/localhost.key
